services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - 4566:4566
      - 4571:4571
    environment:
      - SERVICES=serverless,cloudformation,sts,iam,lambda,s3,sqs,sns,dynamodb,apigateway,events,logs,secretsmanager,ssm,cloudwatch,route53,ec2
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp}/localstack
    volumes:
      - "./scripts/init.sh:/etc/localstack/init/ready.d/00-init.sh"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./lambdas:/lambdas
      - ./localstack/init:/etc/localstack/init/ready.d
      - ./scripts:/scripts
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    depends_on:
      localstack:
        condition: service_healthy
    networks:
      - app_net
    # healthcheck:
    #   test: ["CMD", "curl", "--spider", "http://localhost:8000"]
    #   interval: 10s
    #   retries: 3
  ui:
    container_name: frontend
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app_net
networks:
  app_net:
    driver: bridge