services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - 4566:4566
      - 4571:4571
    environment:
      - SERVICES=serverless,cloudformation,sts,iam,lambda,s3,sqs,sns,dynamodb,apigateway,events,logs,secretsmanager,ssm,cloudwatch,route53,ec2
      - DEBUG=1
    volumes:
      - ./scripts:/scripts
      - ./lambdas:/lambdas
      - ./localstack/init:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app_net

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    depends_on:
      - localstack
    networks:
      - app_net

  ui:
    container_name: frontend
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
